Repository untile/github-changelog-generator, pull requests merged in 2023-08, with the labels that each got.

#13 Fix latest release behaviour and restore default
  README.md
  src/constants/commands.ts
  src/constants/queries.ts
  src/core/fetcher.test.ts
  src/core/fetcher.ts
  src/index.ts
  src/lib/changelog-generator.test.ts
  src/lib/changelog-generator.ts
  src/types.ts
Labels: breaking change, type: bug

#14 Bump dependencies
  .github/workflows/publish.yml
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: type: support

#15 Fix node version
  package.json
Labels: type: bug
