Repository untile/github-changelog-generator, pull requests merged in 2023-04, with the labels that each got.

#4 Add release and publish GitHub actions
  .github/workflows/publish.yml
  .github/workflows/release.yml
  README.md
  package.json
Labels: type: support

#5 Fix publish action npm authentication
  .github/workflows/publish.yml
Labels: type: bug

#6 Fix NPM publish action wrong registry
  .github/workflows/publish.yml
Labels: type: bug, type: support

#7 Fix initial README inconsistencies
  README.md
Labels: type: bug

#8 Rebuild changelog by default
  README.md
  src/constants/commands.ts
  src/index.ts
  src/lib/changelog-generator.test.ts
  src/lib/changelog-generator.ts
  src/types.ts
Labels: type: bug

#10 Fix Homepage URL in Package.json
  package.json
Labels: type: support

#12 Fix error when unable to infer path to changelog
  src/index.ts
Labels: type: bug
